# Generated by Django 5.0.6 on 2024-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=30, null=True)),
                ('marca_producto', models.CharField(max_length=30, null=True)),
                ('codigo_marca', models.CharField(max_length=30, null=True)),
                ('nombre_producto', models.CharField(max_length=40, null=True)),
                ('valor_producto', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_herramienta', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'TipoProducto',
            },
        ),
    ]
