# Generated by Django 5.0.6 on 2024-05-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiHerramientas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_herramienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiHerramientas.tipoproducto'),
        ),
    ]
